metadata:
  sources:
    - name: person_inputs
      params:
        path: output_file1.json
        format: JSON
  transformations:
    - name: validation
      type: validate_fields
      params:
        input: person_inputs
        steps:
          - field: office
            validations:
              - notEmpty
          - field: age
            validations:
              - notNull
        outputs:
          output_ok: validation_ok
          output_notok: validation_notok
    - name: ok_with_date
      type: add_fields
      params:
        input: validation_ok
        steps:
          - name: dt
            function: current_timestamp
          - name: dt2
            function: current_timestamp
        outputs:
          output: final_ok
  outputs:
    - input: final_ok
      name: raw-ok
      params:
        path: raw-ok.json
        format: JSON
        mode: overwrite
    - input: validation_notok
      name: raw-notok
      params:
        path: raw-notok.json
        format: JSON
        mode: overwrite